### ISSUE TITLE
如何处理json类型的返回结果

### ISSUE THREAD

**Issue by zhang382847657** [casatwy/CTNetworkingSwift#1]
API.BaseAPIManager.extension.swift文件第36行

`
  request!.response { (response) in
  }
`
如何实现 
`request?.responseJSON(completionHandler: { (response) in  
 })
`

**Comment by casatwy** [comment]
Networking这里只负责获取原始的data，具体的data的转换，可以放在service里。毕竟不是每家公司都走的json，所以service去处理具体的返回数据。
