### ISSUE TITLE
关于swift版本取消了OC版本的中的errorMessage属性后

### ISSUE THREAD

**Issue by klanf** [casatwy/CTNetworkingSwift#2]
casa大神，你好，我想问个问题：
        在oc版本中，可以通过errorMessage属性在APIManager中编辑具体对错误信息后把具体的错误信息通过manager.errorMessage的方式 给CTNetworkingAPIManagerCallbackDelegate的 managerCallAPIDidFailed:   去做相应的提示之类的操作； 不过swfit版本取消了errorMessage的属性，是因为有更好的替代方式吗？

**Comment by casatwy** [comment]
APIManager的子类实现了validator协议，validator有两个方法，一个是验证参数是否正确，一个是验证返回数据是否正确。【validator中验证返回数据是否正确的方法】跟【errorMessage】功能重复了，且比单纯的errorMessage功能更加强大，所以在swift版本下就去掉了。

**Comment by klanf** [comment]
感谢casa的解答，不过这样的话我还有个疑问就是OC 版本设计了errorType告知错误类型、errorMessage告知具体错误内容，所以errorMessage可以用来返回是哪个key的参数错误了，Swift取消后可以通过什么方式告知 managerCallAPIDidFailed：呢，还是不用告知只需要在validator中内部消化就好了呢？

> APIManager的子类实现了validator协议，validator有两个方法，一个是验证参数是否正确，一个是验证返回数据是否正确。【validator中验证返回数据是否正确的方法】跟【errorMessage】功能重复了，且比单纯的errorMessage功能更加强大，所以在swift版本下就去掉了。

**Comment by casatwy** [comment]
> 感谢casa的解答，不过这样的话我还有个疑问就是OC 版本设计了errorType告知错误类型、errorMessage告知具体错误内容，所以errorMessage可以用来返回是哪个key的参数错误了，Swift取消后可以通过什么方式告知 managerCallAPIDidFailed：呢，还是不用告知只需要在validator中内部消化就好了呢？
> 
> > APIManager的子类实现了validator协议，validator有两个方法，一个是验证参数是否正确，一个是验证返回数据是否正确。【validator中验证返回数据是否正确的方法】跟【errorMessage】功能重复了，且比单纯的errorMessage功能更加强大，所以在swift版本下就去掉了。

validator返回的值如果不是correct，那么就会走到didfail去。因为技术上API请求成功不代表业务上API请求成功，validator就是在技术上调用成功的时候去判断业务上是否调用成功的。
