### ISSUE TITLE
发起请求 参数没有带进去, 打印request也没有带参数呀

### ISSUE THREAD

**Issue by Carrotecho** [casatwy/CTNetworkingSwift#3]

**Comment by casatwy** [comment]
paramSource设置了吗？

**Comment by Carrotecho** [comment]
设置了呀,service里的params都有值,demo里也没有用上params,返回的request自然就没有参数吧

**Comment by casatwy** [comment]
要不你工程开个repo，我clone下来看看？

发自我的iPhone

在 2020年5月22日，19:46，萝卜 <notifications@github.com> 写道：

﻿

设置了呀,service里的params都有值,demo里也没有用上params,返回的request自然就没有参数吧

**Comment by Carrotecho** [comment]
`let request = URLRequest(url: url)`
`do {`
           ` let encodeURLRequest = try URLEncoding.default.encode(request, with: params as Parameters)`
            `return encodeURLRequest`
      `  } catch  {`
           ` return request`
       ` }`
你好,我在TestService.swift的func request()方法里这样返回request,最后的请求就带参数
不好意思,忘记回复了
